version: 2

multi-ecosystem-groups:
  app:
    schedule:
      interval: "cron"
      cronjob: "0 0 1 * *"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 0 1 * *"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    multi-ecosystem-group: app
    patterns:
      - "*"
  - package-ecosystem: "npm"
    directories:
      - "**/*"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    multi-ecosystem-group: app
    patterns:
      - "*"
