version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
