version: "3"

services:
  localstack:
    image: "localstack/localstack"
    ports:
      - 4567-4583:4567-4583
      - 8080:8080
    environment:
      - DEBUG=1
      - SERVICES=lambda,s3,apigateway,cloudformation
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
