---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: Homepage v4.0 s3'

Resources:
  LambdaS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda.takkyuuplayer.com
      AccessControl: Private