---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Master stack: Homepage 4.0'

Resources:
  Feed:
    Type: AWS::Serverless::Function
    Properties:
      Handler: feed
      Runtime: go1.x
      CodeUri: lambda.zip
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /feed
            Method: get

 